/**
 * Autogenerated by Thrift Compiler (0.7.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

namespace SCribe.Thrift
{
  public enum ResultCode
  {
    OK = 0,
    TRY_LATER = 1,
  }
}
